### ISSUE TITLE
python driver.py error, Name or service not known

### ISSUE THREAD

**Issue by lengyueyang** [gregsexton/ob-ipython#109]
I use emacs25.2, org-mode 9.05, when upgrade the system, ob-ipython is not work, when python driver.py, the error as follows, everyone knows why ?

$ python .emacs.d/elpa/ob-ipython-20160918.1001/driver.py 
Traceback (most recent call last):
  File ".emacs.d/elpa/ob-ipython-20160918.1001/driver.py", line 167, in <module>
    main(sys.argv)
  File ".emacs.d/elpa/ob-ipython-20160918.1001/driver.py", line 163, in main
    app.listen(args.port)
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1943, in listen
    server.listen(port, address)
  File "/usr/lib/python3.6/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python3.6/site-packages/tornado/netutil.py", line 156, in bind_sockets
    0, flags)):
  File "/usr/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by lengyueyang** [comment]
when I change my hostname to "127.0.0.1", it OK.
