### ISSUE TITLE
Missing .json extension for the connection file

### ISSUE THREAD

**Issue by fradav** [gregsexton/ob-ipython#19]
`ERROR:tornado.application:Uncaught exception POST /execute/mysession (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:9988', method='POST', uri='/execute/mysession', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Encoding': 'gzip', 'Mime-Version': '1.0', 'Accept': '*/*', 'Content-Length': '60', 'Host': 'localhost:9988', 'User-Agent': 'URL/Emacs', 'Connection': 'keep-alive', 'Extension': 'Security/Digest Security/SSL'})
Traceback (most recent call last):
  File "c:\Users\Fradav\Documents\Dev\Python\Miniconda3\lib\site-packages\tornado\web.py", line 1369, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "c:\Users\Fradav\Documents\Dev\Python\Miniconda3\lib\site-packages\tornado\web.py", line 1572, in wrapper
    result = method(self, *args, **kwargs)
  File "c:/Users/Fradav/AppData/Roaming/.emacs.d/elpa/ob-ipython-20150704.457/driver.py", line 71, in post
    c = get_client(name)
  File "c:/Users/Fradav/AppData/Roaming/.emacs.d/elpa/ob-ipython-20150704.457/driver.py", line 54, in get_client
    clients[name] = create_client(name)
  File "c:/Users/Fradav/AppData/Roaming/.emacs.d/elpa/ob-ipython-20150704.457/driver.py", line 42, in create_client
    cf = find_connection_file('emacs-' + name)
  File "c:\Users\Fradav\Documents\Dev\Python\Miniconda3\lib\site-packages\IPython\kernel\connect.py", line 224, in find_connection_file
    raise IOError("Could not find %r in %r" % (filename, security_dir))
OSError: Could not find 'emacs-mysession' in 'C:\\Users\\Fradav\\AppData\\Roaming\\.ipython\\profile_default\\security'
ERROR:tornado.access:500 POST /execute/mysession (127.0.0.1) 17.60ms
`

Just add  `+ '.json'` there :
`    cf = find_connection_file('emacs-' + name)`
and it works.

**Comment by gregsexton** [comment]
Interesting. I haven't seen this before. Which version of IPython are you running? I think a bunch of stuff broke with version 4.

**Comment by smartass101** [comment]
I think it works well with Jupyter >=1.0 and IPython >= 4.0.

**Comment by gregsexton** [comment]
I think this should be resolved with the latest version of the code. I'm going to close but feel free to message or reopen if this is still causing you a problem.
