### ISSUE TITLE
Connection to server via ssh

### ISSUE THREAD

**Issue by MarcoHassan** [gregsexton/ob-ipython#212]
Hi I am not sure this is a strict related ob-ipython issue but I was wondering if you could help.

I copied the kernel.json of the remote machine on my local and I am trying to connect it via

$ jupyter-console --existing ./kernel_studio.json --ssh dsxuser@IP

...

I get the following output:

[ZMQTerminalIPythonApp] ERROR | Failed to load connection file: '/home/mhassan/Scrivania/kernel_studio.json'
Traceback (most recent call last):
  File "/home/mhassan/.local/lib/python3.6/site-packages/jupyter_client/consoleapp.py", line 193, in init_connection_file
    self.load_connection_file()
  File "/home/mhassan/.local/lib/python3.6/site-packages/jupyter_client/connect.py", line 494, in load_connection_file
    info = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)

Any idea of what the issue might be?

Thanks in advance!

**Comment by MarcoHassan** [comment]
And btw: thanks for the awesome package!

**Comment by MarcoHassan** [comment]
ok bad me. quotes were removed in the json when saving it via echo >> xx.json.
