### ISSUE TITLE
Trying to parse HTTP response code in odd buffer

### ISSUE THREAD

**Issue by justmytwospence** [gregsexton/ob-ipython#22]
I receive the following messages when trying to run IPython code blocks:

```
executing Ipython code block...
Making python-shell-interpreter local to *Python* while let-bound!
Making python-shell-interpreter-args local to *Python* while let-bound!
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
Contacting host: localhost:9988
url-http-parse-response: Trying to parse HTTP response code in odd buffer:  *http localhost:9988*
```

I am on OSX and Emacs 24.5. Any ideas?

**Comment by singletS** [comment]
I'm also getting the "trying to parse...strange buffer" error as of upgrading to Emacs 25.0.50.2, linux.

Looking at ob-ipython-driver buffer:
```
Traceback (most recent call last):
  File ".emacs.d/elpa/ob-ipython-20150627.532/driver.py", line 2, in <module>
    from IPython.kernel.connect import find_connection_file
ImportError: No module named IPython.kernel.connect

Process ob-ipython-driver exited abnormally with code 1
```
I'm using anaconda python3 environment:
```   python-shell-interpreter "~/local/anaconda3/bin/ipython"```

Using emacs 24.5.50.1 on another linux machine, ob-ipython seems to work fine.

**Comment by stephenjbarr** [comment]
Seeing the same issue with emacs 24. This is from messages:

```
executing Ipython code block...
Shell native completion is disabled, using fallback
Contacting host: localhost:9988
url-http-parse-response: Trying to parse HTTP response code in odd buffer:  *http localhost:9988*
org-babel-load-session:ipython: Currently unsupported.
executing Ipython code block...
Contacting host: localhost:9988
url-http-parse-response: Trying to parse HTTP response code in odd buffer:  *http localhost:9988*-560521
Mark set
Quit
executing Ipython code block...
Contacting host: localhost:9988
url-http-parse-response: Trying to parse HTTP response code in odd buffer:  *http localhost:9988*-999358
Mark set

```

This is from the driver buffer:
```
Process ob-ipython-driver exited abnormally with code 1
Traceback (most recent call last):
  File "/home/stevejb/.emacs.d/elpa/ob-ipython-20150704.457/driver.py", line 1, in <module>
    from IPython.lib.kernel import find_connection_file
ImportError: No module named IPython.lib.kernel
```

**Comment by stephenjbarr** [comment]
It seems like the common thread in this issue is using python 3 instead of python 2, but driver.py is launched with whatever `python` means in the system prompt, which is most likely python 2.

**Comment by justmytwospence** [comment]
I don't even have a driver buffer from what I can tell. Here is my process-list though:

```
Python          run     *Python*        /dev/ttys006 ipython console --existing emacs-*IPython*.json
idna            run     --              /dev/ttys003 idn --quiet --idna-to-ascii --usestd3asciirules
kernel-*IPyt... run     *ob-ipython-... /dev/ttys005 ipython kernel --IPKernelApp.connection_file=emacs-*IPython*.json
localhost       failed   *http local... --           (network connection to localhost)
```

**Comment by gregsexton** [comment]
Hmm.. There shouldn't be any issue between python 2 and 3. I use both on different systems. Are you guys running IPython 4?

**Comment by gregsexton** [comment]
I'm 99% sure this is due to IPython 4. I've just fixed the repo to support this. Pull the latest version of the code and make sure you have jupyter installed. Hopefully this fixes the issue being seen here. See #26 too.

I'm going to close this but if things are still not working feel free to reopen.

Thanks,

Greg

**Comment by justmytwospence** [comment]
Works now, thanks!

**Comment by thoo** [comment]
Now on my mac with anaconda python, I get the same error message. Any help?

**Comment by gregsexton** [comment]
Have you looked at the readme? It was updated recently to give more info on required dependencies. Can you check that you have the correct versions of everything?

**Comment by thoo** [comment]
I just check all the dependencies and still getting the errors.

````
Debugger entered--Lisp error: (error "Trying to parse HTTP response code in odd buffer:  *http localhost:9988*")
  signal(error ("Trying to parse HTTP response code in odd buffer:  *http localhost:9988*"))
  error("Trying to parse HTTP response code in odd buffer: %s" " *http localhost:9988*")
  url-http-parse-response()
  ob-ipython--execute-request("  %matplotlib inline\n  import matplotlib.pyplot as plt" "default")
  org-babel-execute:ipython("  %matplotlib inline\n  import matplotlib.pyplot as plt" ((:comments . "") (:shebang . "") (:cache . "no") (:padline . "") (:noweb . "no") (:tangle . "no") (:exports . "both") (:results . "output replace") (:hlines . "no") (:session) (:result-type . output) (:result-params "replace" "output") (:rowname-names) (:colname-names)))
