### ISSUE TITLE
Not working with IPython 4. and Jupyter

### ISSUE THREAD

**Issue by Titan-C** [gregsexton/ob-ipython#26]
I recently upgraded my Ipython versions and when evaluating a codeblock the system would stand still trying to: `Contacting host: localhost:9988`

If I kill the process I can read in `ob-ipython-oi-ipython-driver`
```
/home/oscar/miniconda/envs/dev/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
['/home/oscar/.emacs.d/elpa/ob-ipython-20150704.457/driver.py', '9988']
```
Which is not much information for me.
I change nevertheles `IPython.kernel` for `jupyter_client`. That did not improve things.
When evaluating a block, it gets stuck in the same step.

If I give the block a session name I do get to an error the `ob-ipython-debug` says
```
HTTP/1.1 500 Internal Server Error
Date: Sat, 22 Aug 2015 13:43:07 GMT
Content-Length: 93
Content-Type: text/html; charset=UTF-8
Server: TornadoServer/4.2.1

<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
```
and  `ob-ipython-oi-ipython-driver`
```
ERROR:tornado.application:Uncaught exception POST /execute/cars (::1)
HTTPServerRequest(protocol='http', host='localhost:9988', method='POST', uri='/execute/cars', version='HTTP/1.1', remote_ip='::1', headers={'Content-Length': '165', 'Accept-Encoding': 'gzip', 'Extension': 'Security/Digest Security/SSL', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'URL/Emacs', 'Host': 'localhost:9988', 'Mime-Version': '1.0'})
Traceback (most recent call last):
  File "/home/oscar/miniconda/envs/dev/lib/python2.7/site-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/home/oscar/miniconda/envs/dev/lib/python2.7/site-packages/tornado/web.py", line 1572, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/oscar/.emacs.d/elpa/ob-ipython-20150704.457/driver.py", line 71, in post
    c = get_client(name)
  File "/home/oscar/.emacs.d/elpa/ob-ipython-20150704.457/driver.py", line 54, in get_client
    clients[name] = create_client(name)
  File "/home/oscar/.emacs.d/elpa/ob-ipython-20150704.457/driver.py", line 42, in create_client
    cf = find_connection_file('emacs-' + name)
  File "/home/oscar/miniconda/envs/dev/lib/python2.7/site-packages/ipykernel/connect.py", line 85, in find_connection_file
    return jupyter_client.find_connection_file(filename, path=['.', security_dir])
  File "/home/oscar/miniconda/envs/dev/lib/python2.7/site-packages/jupyter_client/connect.py", line 185, in find_connection_file
    raise IOError("Could not find %r in %r" % (filename, path))
IOError: Could not find u'emacs-cars' in ['.', u'/home/oscar/.ipython/profile_default/security']
ERROR:tornado.access:500 POST /execute/cars (::1) 3.85ms
```

**Comment by gregsexton** [comment]
Thanks for letting me know. It's going to be fun fixing this and maintaining support for older versions. :(

**Comment by gregsexton** [comment]
Ok, got a fix in place. You'll need to pull the latest repo and also install jupyter (available in pip, if not elsewhere).

I've now made IPython 4 a minimum dependency going forward.

Let me know if you still have problems.
