### ISSUE TITLE
Cannot run the sample code 

### ISSUE THREAD

**Issue by xin-jin** [gregsexton/ob-ipython#87]
Everything is update-to-date (in particular, ipython 5.1.0). When I run an arbitrary code sample, I get the following in `*Python*`

```
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
Traceback (most recent call last):
  File "/home/xin/anaconda/bin/ipython", line 6, in <module>
    sys.exit(IPython.start_ipython())
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/core/application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 488, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/core/application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 426, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/jupyter_console/app.py", line 138, in initialize
    self.init_shell()
  File "/home/xin/anaconda/lib/python3.5/site-packages/jupyter_console/app.py", line 111, in init_shell
    client=self.kernel_client,
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/jupyter_console/interactiveshell.py", line 135, in __init__
    super(ZMQTerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 396, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 495, in __init__
    self.init_completer()
  File "/home/xin/anaconda/lib/python3.5/site-packages/jupyter_console/interactiveshell.py", line 160, in init_completer
    if self.has_readline:
AttributeError: 'ZMQTerminalInteractiveShell' object has no attribute 'has_readline'

Process Python exited abnormally with code 1
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
Traceback (most recent call last):
  File "/home/xin/anaconda/bin/ipython", line 6, in <module>
    sys.exit(IPython.start_ipython())
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/core/application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 488, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/core/application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 426, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/jupyter_console/app.py", line 138, in initialize
    self.init_shell()
  File "/home/xin/anaconda/lib/python3.5/site-packages/jupyter_console/app.py", line 111, in init_shell
    client=self.kernel_client,
  File "/home/xin/anaconda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/jupyter_console/interactiveshell.py", line 135, in __init__
    super(ZMQTerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 396, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/xin/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 495, in __init__
    self.init_completer()
  File "/home/xin/anaconda/lib/python3.5/site-packages/jupyter_console/interactiveshell.py", line 160, in init_completer
    if self.has_readline:
AttributeError: 'ZMQTerminalInteractiveShell' object has no attribute 'has_readline'

Process Python exited abnormally with code 1
```

**Comment by gregsexton** [comment]
Just fixed this.
